# Generated by Django 4.1.2 on 2024-04-03 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('paradigm', models.CharField(max_length=100)),
                ('modality', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('subject', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=50)),
                ('trialid', models.CharField(max_length=50)),
                ('trialsample', models.IntegerField()),
                ('trialsfreq', models.IntegerField()),
                ('trialchan', models.TextField()),
                ('sexual', models.CharField(max_length=1)),
                ('age', models.IntegerField()),
                ('scibackground', models.BooleanField()),
                ('sleephours', models.FloatField()),
                ('sleepqaulity', models.FloatField()),
                ('brainhealth', models.CharField(max_length=100)),
                ('workout', models.FloatField()),
                ('exptime', models.FloatField()),
                ('trialbaseline', models.IntegerField()),
                ('npy_file_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
