# Generated by Django 4.1.2 on 2024-04-03 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bciDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialdata',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
