# Generated by Django 4.1.2 on 2024-04-03 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bciDB', '0002_alter_trialdata_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trialdata',
            name='scibackground',
            field=models.IntegerField(),
        ),
    ]
